apiVersion: batch/v1
kind: Job
metadata:
  name: rsekube-train-mnist-job
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/zihaozhou/nautilus_tutorial:jupyterhub
        command: ["/bin/bash","-c"]
        args: ["git clone https://github.com/thielec/rse-kube-pytorch-mnist.git project; cd project;
                python train.py --save-model;
                mv mnist_cnn.pt /output"]
        volumeMounts:
        - mountPath: /output
          name: mnist-test-volume
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "8G"
            cpu: "4"
          requests:
            nvidia.com/gpu: "1"
            memory: "8G"
            cpu: "4"
      restartPolicy: Never
      volumes:
        - name: mnist-test-volume
          persistentVolumeClaim:
            claimName: mnist-test-volume
